---

configure_mas: yes
configure_dotfiles: no
configure_sudoers: no
configure_terminal: no
configure_osx: no

homebrew_installed_packages:
  - ansible-lint
  - autojump
  - awscli
  - aws-shell
  - bash-completion
  - colordiff
  - curl
  - docker-completion
  - dockutil
  - fish
  - git
  - htop
  - httpie
  - hugo
  - jq
  - mackup
  - mvnvm
  - neovim
  - oath-toolkit
  - openshift-cli
  - openssl
  - pv
  - qemu
  - smartmontools
  - terraform
  - tree
  - vagrant-completion
  - vim
  - watch
  - wget
  - youtube-dl
homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - buo/cask-upgrade

homebrew_cask_apps:
  - atom
  - authy
  - battle-net
  - bettertouchtool
  - blue-jeans-browser-plugin
  - blue-jeans-launcher
  - carbon-copy-cloner
  - dash
  - discord
  - docker
  - firefox
  - flux
  - google-chrome
  - google-photos-backup-and-sync
  - grammarly
  - iina
  - intel-power-gadget
  - iterm2
  - itsycal
  - java
  - keepingyouawake
  - keybase
  - minikube
  - nvALT
  - openemu
  - plexamp
  - postico
  - postman
  - pycharm-ce
  - QLMarkdown
  - rocket-chat
  - sequel-pro
  - signal
  - slack
  - spotify
  - steam
  - teamviewer
  - tunnelblick
  - tweeten
  - twitch
  - vagrant
  - vagrant-manager
  - virtualbox
  - vlc
  - wireshark
  - xquartz
#  - wireshark-chmodbpf
#  - caskroom/fonts/font-hack
#  - caskroom/fonts/font-hack-nerd-font-mono
mas_email: ""
mas_password: ""
mas_installed_apps:
  - { id: 408981434, name: "iMovie" }
  - { id: 409183694, name: "Keynote" }
  - { id: 405399194, name: "Kindle" }
  - { id: 715768417, name: "Microsoft Remote Desktop" }
  - { id: 409203825, name: "Numbers" }
  - { id: 409201541, name: "Pages" }
  - { id: 639968404, name: "Parcel" }
  - { id: 1160374471, name: "PiPifier" }
#  - { id: 497799835, name: "Xcode" }

dockitems_remove_all: true
dockitems_enabled:
  - name: Safari
    path: "/Applications/Safari.app"
    pos: 1
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 2
  - name: Firefox
    path: "/Applications/Firefox.app"
    pos: 3
  - name: iTerm
    path: "/Applications/iTerm.app"
    pos: 4
  - name: TeamViewer
    path: "/Applications/TeamViewer.app"
    pos: 5
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 6
  - name: Rocket.Chat+
    path: "/Applications/Rocket.Chat+.app"
    pos: 7
  - name: Atom
    path: "/Applications/Atom.app"
    pos: 8
  - name: Postman
    path: "/Applications/Postman.app"
    pos: 9
  - name: Mail
    path: "/Applications/Mail.app"
    pos: 10
  - name: Discord
    path: "/Applications/Discord.app"
    pos: 11
  - name: TweetDeck
    path: "/Applications/TweetDeck.app"
    pos: 12
  - name: Steam
    path: "/Applications/Steam.app"
    pos: 13
  - name: Wireshark
    path: "/Applications/Wireshark.app"
    pos: 14
  - name: IINA
    path: "/Applications/IINA.app"
    pos: 15
  - name: VirtualBox
    path: "/Applications/VirtualBox.app"
    pos: 16
  - name: OpenEmu
    path: "/Applications/OpenEmu.app"
    pos: 17
  - name: Grammarly
    path: "/Applications/Grammarly.app"
    pos: 18
  - name: Messages
    path: "/Applications/Messages.app"
    pos: 19
  - name: Spotify
    path: "/Applications/Spotify.app"
    pos: 20
  - name: Photos
    path: "/Applications/Photos.app"
    pos: 21
  - name: App Store
    path: "/Applications/App Store.app"
    pos: 22
#pip_packages:
#  - name: mkdocs
